[[plugins]]
repo = 'junegunn/goyo.vim'
on_cmd = 'Goyo'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['javascript', 'javascriptreact', 'typescript', 'typescriptreact', 'html']

[[plugins]]
repo = 'junegunn/gv.vim'
on_cmd = 'GV'

[[plugins]]
repo = 'junegunn/limelight.vim'
hook_add = 'source ~/nvimfiles/plugins/limelight.rc.vim'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'Tagbar'


[[plugins]]
repo = 'previm/previm'
on_cmd = 'PrevimOpen'
depends = ['open-browser.vim']
hook_add = '''
let g:previm_show_header = 0
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_cmd = 'TableModeToggle'
hook_add = '''
let g:table_mode_corner = '|'
'''

[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css']
