[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/nvimfiles/plugins/denite.rc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['denite.nvim']

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/nvimfiles/plugins/defx.rc.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'source ~/nvimfiles/plugins/deoplete.rc.vim'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
hook_post_update = '''
if has('win32')
    let cmd = 'powershell.exe .\install.ps1'
elseif has('mac')
    let cmd = './install.sh'
else
    echo 'deoplete-tabnine is disable'
    let cmd = ''
endif
let g:dein#plugin.build = cmd
'''
if = "has('win32') || has('mac')"

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
au MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'kana/vim-submode'
hook_add = 'source ~/nvimfiles/plugins/submode.rc.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/nvimfiles/plugins/fugitive.rc.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/nvimfiles/plugins/gitgutter.rc.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char_list = ['|', '¦']
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/nvimfiles/plugins/vim-airline.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']
hook_add = "let g:airline_theme='iceberg'"

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = 'source ~/nvimfiles/plugins/ale.rc.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source ~/nvimfiles/plugins/easymotion.rc.vim'

[[plugins]]
repo = 'mbbill/undotree'
