[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/nvimfiles/plugins/denite.rc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['denite.nvim']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'source ~/nvimfiles/plugins/deoplete.rc.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['async.vim']
hook_add = 'source ~/nvimfiles/plugins/vim-lsp.rc.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = ['deoplete.nvim', 'vim-lsp']

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
hook_post_update = '''
if has('win32')
    let cmd = 'powershell.exe .\install.ps1'
elseif has('mac')
    let cmd = './install.sh'
else
    echo 'deoplete-tabnine is disable'
    let cmd = ''
endif
let g:dein#plugin.build = cmd
'''
if = "has('win32') || has('mac')"

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
au MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/nvimfiles/plugins/nerdtree.rc.vim'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']
hook_add = 'source ~/nvimfiles/plugins/nerdtree-git-plugin.rc.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'kana/vim-submode'
hook_add = 'source ~/nvimfiles/plugins/submode.rc.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/nvimfiles/plugins/fugitive.rc.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/nvimfiles/plugins/gitgutter.rc.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'source ~/nvimfiles/plugins/vim-indent-guides.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/nvimfiles/plugins/vim-airline.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']
hook_add = "let g:airline_theme='jellybeans'"

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/nvimfiles/plugins/ale.rc.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source ~/nvimfiles/plugins/easymotion.rc.vim'

[[plugins]]
repo = 'mbbill/undotree'
