# dein
[[plugins]]
repo = 'Shougo/dein.vim'

# nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
source ~/nvimfiles/plugins/nerdtree.rc.vim
'''

# denite
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = 'neomru.vim'
hook_add = '''
source ~/nvimfiles/plugins/denite.rc.vim
'''

# neomru
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.vim'

# deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
source ~/nvimfiles/plugins/deoplete.rc.vim
'''

# vim-submode
[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
source ~/nvimfiles/plugins/submode.rc.vim
'''

# vim-fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
source ~/nvimfiles/plugins/vim-fugitive.rc.vim
'''

# vim-gitgutter
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/nvimfiles/plugins/vim-gitgutter.rc.vim
'''

# vim-intent-guides
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides.git'
hook_add = '''
source ~/nvimfiles/plugins/vim-indent-guides.rc.vim
'''

# vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes', 'vim-fugitive']
hook_add = '''
source ~/nvimfiles/plugins/vim-airline.rc.vim
'''

# vim-airline-themes
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
let g:airline_theme='jellybeans'
'''

# vim-surround
[[plugins]]
repo = 'tpope/vim-surround'

# neosnippet
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
hook_add = '''
source ~/nvimfiles/plugins/neosnippet.rc.vim
'''

# neosnippet-snippets
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# vim-signature
[[plugins]]
repo = 'kshenoy/vim-signature'

# tagbar
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
source ~/nvimfiles/plugins/tagbar.rc.vim
'''

# ale
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/nvimfiles/plugins/ale.rc.vim
'''

# easymotion
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
source ~/nvimfiles/plugins/easymotion.rc.vim
'''

# colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
set background=dark
autocmd VimEnter * nested colorscheme iceberg
'''
