# dein
[[plugins]]
repo = 'Shougo/dein.vim'

# vim-precious
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# context_filetype
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
source ~/nvimfiles/plugins/nerdtree.rc.vim
'''

# denite
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = 'neomru.vim'
hook_add = '''
source ~/nvimfiles/plugins/denite.rc.vim
'''

# neomru
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.vim'

# deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
source ~/nvimfiles/plugins/deoplete.rc.vim
'''

# vim-submode
[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
source ~/nvimfiles/plugins/submode.rc.vim
'''

# vim-fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
source ~/nvimfiles/plugins/vim-fugitive.rc.vim
'''

# vim-gitgutter
[[plugins]]
repo = 'airblade/vim-gitgutter'
